/**
 * Generates three reviews per Volta product via the AI Gateway and writes
 * them to `src/lib/catalog/volta-reviews.ts`. Needs `AI_GATEWAY_API_KEY` in
 * `.env.local`.
 *
 *   node --env-file=.env.local --experimental-strip-types scripts/volta-reviews.ts
 */
import { writeFile } from "node:fs/promises"

import { generateObject } from "ai"
import { z } from "zod"

import { products } from "../src/lib/catalog/volta.ts"
import type { Product, Review } from "../src/lib/catalog/types.ts"

const MODEL = "anthropic/claude-sonnet-5"
const OUT = "src/lib/catalog/volta-reviews.ts"
const CONCURRENCY = 6

const reviewSchema = z.object({
  author: z
    .string()
    .describe(
      'First name and last initial, e.g. "Sanne V." Dutch or wider European names.',
    ),
  rating: z.number().int().min(3).max(5),
  title: z.string().describe("Two to six words. Specific, not generic praise."),
  body: z
    .string()
    .describe(
      "One or two sentences, 15 to 35 words. One concrete detail from actually using it.",
    ),
  date: z
    .string()
    .describe("ISO date YYYY-MM-DD between 2026-03-01 and 2026-09-10."),
  verified: z
    .boolean()
    .describe("true for most; false for one in five at most."),
  context: z
    .string()
    .optional()
    .describe(
      'Short training context, e.g. "Marathon, 3:12" or "Lifting 4x a week". Only on about one review in three.',
    ),
})

const schema = z.object({
  reviews: z.array(reviewSchema).length(3),
})

const SYSTEM = `You write short, believable customer reviews for a European sports nutrition shop called Volta.
Plain, first-person, understated. British spelling. No exclamation marks, no marketing words, no emoji.
Each of the three reviews must differ in angle: taste or mixability, effect during training, and value or packaging are typical angles.
Ratings should sit around the product's mean rating: mostly 5s and 4s, with a 4 or a 3 carrying one specific, minor gripe.
Prices are in EUR. Never mention other brands.`

function describe(product: Product) {
  const attributes = Object.entries(product.attributes)
    .map(([key, value]) => `${key}: ${value}`)
    .join(", ")
  return [
    `Product: ${product.name}`,
    `Category: ${product.category}`,
    `Attributes: ${attributes}`,
    `Description: ${product.description}`,
    `Tags: ${product.tags.join(", ")}`,
    `Price: €${(product.price / 100).toFixed(2)}`,
    product.rating
      ? `Mean rating: ${product.rating} from ${product.reviewCount} reviews`
      : "",
  ]
    .filter(Boolean)
    .join("\n")
}

async function reviewsFor(product: Product): Promise<Review[]> {
  const { object } = await generateObject({
    model: MODEL,
    schema,
    system: SYSTEM,
    prompt: `Write three reviews for this product.\n\n${describe(product)}`,
  })

  return object.reviews
    .sort((a, b) => b.date.localeCompare(a.date))
    .map((review, index) => ({
      id: `r-${product.slug}-${index + 1}`,
      product: product.slug,
      ...review,
    }))
}

async function run() {
  const queue = [...products]
  const results = new Map<string, Review[]>()

  async function worker() {
    for (let product = queue.shift(); product; product = queue.shift()) {
      results.set(product.slug, await reviewsFor(product))
      process.stdout.write(`  ${product.slug}\n`)
    }
  }

  await Promise.all(Array.from({ length: CONCURRENCY }, worker))

  // Keep catalog order so the diff stays readable across runs.
  const reviews = products.flatMap((product) => results.get(product.slug) ?? [])

  const source = `import type { Review } from "./types"

/**
 * Generated by \`scripts/volta-reviews.ts\`; edit the prompt there and rerun
 * rather than editing this file by hand.
 */
export const reviews: Review[] = ${JSON.stringify(reviews, null, 2)}
`

  await writeFile(OUT, source)
  console.log(`Wrote ${reviews.length} reviews to ${OUT}`)
}

run().catch((error) => {
  console.error(error)
  process.exit(1)
})
